Modified aggregate function
danitseitlin/redis-modules-sdk pull request #91
Opened 2021-05-24 20:03 UTC by ashleighplummer

to include multiple properties for GroupBy, Sortby, and Apply.

2021-05-25 05:43 UTC, danitseitlin requested changes

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +                    parameters.groupby.property.split(" ").forEach((property) => {
What happens if there is only one property? Won't you have an error on the split function?

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +declare type SortByProperty = {
Instead of declare, write export. Also, don't forget to add it to the index.ts file

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +declare type Expressions = {
Same as above

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +declare type SortByProperty = {
Please add description to all types including their properties

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +        nargs: string;
In types,please use , instead of ;

2021-05-25 05:43 UTC, danitseitlin commented on modules/redisearch.ts
> +            if (parameters.load !== undefined) {
I don't see a reason to add spaces after the if before brackets while all the code is done without it.  Just creates inconsistency in the code.

2021-05-27 23:41 UTC, danitseitlin commented on modules/redisearch.ts
> +                    parameters.groupby.property.split(" ").forEach((property) => {
Isn't it better if this is a string array ?

2021-06-07 06:57 UTC, danitseitlin commented
Due to the fact that these changes are important but you we're not responsive to fix the PR requested changes, I've made similar changes and pushed them to master. (https://github.com/danitseitlin/redis-modules-sdk/pull/98)

2021-06-07 06:57 UTC, closed without merging

2021-06-17 16:50 UTC, ashleighplummer commented
Hi Dan,

Sorry for the unresponsiveness I’ve been extremely busy the past couple of weeks.

Yeah, these changes make sense and I’ve noticed you’ve updated it in the main code base. Awesome!

I’ll continue to use the package, communicate any findings and suggest new changes.

Ash 🙂
________________________________
From: Dani Tseitlin ***@***.***>
Sent: 25 May 2021 05:43
To: danitseitlin/redis-modules-sdk ***@***.***>
Cc: Ashleigh Plummer ***@***.***>; Author ***@***.***>
Subject: Re: [danitseitlin/redis-modules-sdk] Modified aggregate function (#91)


@danitseitlin requested changes on this pull request.

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638467128>:

>                      args.push(parameters.groupby.nargs);
-                if(parameters.groupby.property !== undefined)
-                    args.push(parameters.groupby.property);
+                if (parameters.groupby.property !== undefined) {
+                    parameters.groupby.property.split(" ").forEach((property) => {


What happens if there is only one property? Won't you have an error on the split function?

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638467762>:

>      limit?: {
-        offset: string,
-        numberOfResults: number
-    },
-    filter?: string
-}
+        offset: string;
+        numberOfResults: number;
+    };
+    filter?: string;
+};
+
+
+declare type SortByProperty = {


Instead of declare, write export. Also, don't forget to add it to the index.ts file

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638467812>:

> -    },
-    filter?: string
-}
+        offset: string;
+        numberOfResults: number;
+    };
+    filter?: string;
+};
+
+
+declare type SortByProperty = {
+    fieldName: string,
+    sort: 'ASC' | 'DESC';
+};
+
+declare type Expressions = {


Same as above

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638468009>:

>      limit?: {
-        offset: string,
-        numberOfResults: number
-    },
-    filter?: string
-}
+        offset: string;
+        numberOfResults: number;
+    };
+    filter?: string;
+};
+
+
+declare type SortByProperty = {


Please add description to all types including their properties

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638468394>:

>      load?: {
-        nargs: string,
-        property: string
-    },
+        nargs: string;


In types,please use , instead of ;

________________________________

In modules/redisearch.ts<https://github.com/danitseitlin/redis-modules-sdk/pull/91#discussion_r638469635>:

> @@ -175,54 +175,60 @@ export class Redisearch extends Module {
     async aggregate(index: string, query: string, parameters?: FTAggregateParameters): Promise<number> {
         let args: string[] = [index, query];
         if(parameters !== undefined) {
-            if(parameters.load !== undefined) {
-                args.push('LOAD')
-                if(parameters.load.nargs !== undefined)
+            if (parameters.load !== undefined) {


I don't see a reason to add spaces after the if before brackets while all the code is done without it. Just creates inconsistency in the code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/danitseitlin/redis-modules-sdk/pull/91#pullrequestreview-667404919>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQDAMCUFON6SGIX3IJWZ4CLTPM2HTANCNFSM45N2Y3LA>.

2021-06-17 16:57 UTC, danitseitlin commented
@ashleighplummer Hi there, all well understood and good. I just saw these changes are very good and saw it as important to push, so unfortunately I went and did it myself. But thank you for the pointing out and using my pkg! 🔥 🌟

2021-06-17 17:01 UTC, ashleighplummer commented
🙌 Your work enables me to do more so thank you 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Dani ***@***.***>
Sent: 17 June 2021 17:57
To: ***@***.***>
Cc: Ashleigh ***@***.***>; ***@***.***>
Subject: Re: [danitseitlin/redis-modules-sdk] Modified aggregate function (#91)


@ashleighplummer<https://github.com/ashleighplummer> Hi there, all well understood and good. I just saw these changes are very good and saw it as important to push, so unfortunately I went and did it myself. But thank you for the pointing out and using my pkg! 🔥 🌟

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/danitseitlin/redis-modules-sdk/pull/91#issuecomment-863404686>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQDAMCULLACX55RSDBWQMLTTTISOPANCNFSM45N2Y3LA>.